version: "3.8"

services:
  pg-database:
    image: postgres:13
    container_name: pg-database-1
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin-2:
    image: dpage/pgadmin4
    container_name: pgadmin-1
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    depends_on:
      - pg-database
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
